// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oikos.Infrastructure.Data;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(OikosDbContext))]
    [Migration("20260123120401_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Oikos.Domain.Entities.CompanyCheck.CompanyCheckRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasComment("Charged amount");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasComment("Original company name provided by user");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("Request creation time");

                    b.Property<string>("CreditsafeCompanyId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasComment("Creditsafe company identifier");

                    b.Property<string>("CreditsafeCountryCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasComment("Creditsafe country code");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasComment("Currency code");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasComment("Customer email for Stripe");

                    b.Property<DateTime?>("PaymentConfirmedAt")
                        .HasColumnType("TEXT")
                        .HasComment("Payment confirmation time");

                    b.Property<string>("ReportDownloadToken")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasComment("Unique download token for the report PDF");

                    b.Property<string>("ReportJson")
                        .HasColumnType("TEXT")
                        .HasComment("Serialized detailed report");

                    b.Property<DateTime?>("ReportPdfGeneratedAt")
                        .HasColumnType("TEXT")
                        .HasComment("Timestamp when the PDF report was generated");

                    b.Property<string>("ReportPdfPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasComment("Relative path of the generated PDF report");

                    b.Property<string>("SelectedCompanyJson")
                        .HasColumnType("TEXT")
                        .HasComment("Serialized summary of selected company");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasComment("Request status");

                    b.Property<string>("StripeCheckoutSessionId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasComment("Stripe checkout session identifier");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasComment("Stripe payment intent identifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("Last update time");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasComment("User identifier");

                    b.HasKey("Id");

                    b.ToTable("CompanyCheckRequests", t =>
                        {
                            t.HasComment("Company check requests and reports");
                        });
                });

            modelBuilder.Entity("Oikos.Domain.Entities.Invoice.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Amount")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasComment("Amount as provided");

                    b.Property<string>("Company")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasComment("Company name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("Create time");

                    b.Property<string>("Currency")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasComment("Currency code");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasComment("Description");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasComment("Stored file path (relative to web root)");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("TEXT")
                        .HasComment("Invoice date");

                    b.Property<string>("PowerOfAttorneyPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasComment("Stored power of attorney file path (relative to web root)");

                    b.Property<int>("PrimaryStatus")
                        .HasColumnType("INTEGER")
                        .HasComment("Cached current primary status");

                    b.Property<int>("StageId")
                        .HasColumnType("INTEGER")
                        .HasComment("Current workflow stage identifier");

                    b.Property<string>("TicketNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasComment("Ticket number");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("Update time");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasComment("Owner User Id");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.ToTable("Invoices", t =>
                        {
                            t.HasComment("User Invoices");
                        });
                });

            modelBuilder.Entity("Oikos.Domain.Entities.Invoice.InvoiceStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT")
                        .HasComment("Preferred MudBlazor color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("Create time");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasComment("Detailed description of the stage");

                    b.Property<string>("DescriptionDe")
                        .HasColumnType("TEXT")
                        .HasComment("Detailed description of the stage (German)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER")
                        .HasComment("Display order");

                    b.Property<string>("Icon")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasComment("MudBlazor icon identifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasComment("Stage display name");

                    b.Property<string>("NameDe")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasComment("Stage display name (German)");

                    b.Property<string>("NextSteps")
                        .HasColumnType("TEXT")
                        .HasComment("Recommended next steps for the user");

                    b.Property<string>("NextStepsDe")
                        .HasColumnType("TEXT")
                        .HasComment("Recommended next steps for the user (German)");

                    b.Property<int>("PrimaryStatus")
                        .HasColumnType("INTEGER")
                        .HasComment("Primary status classification");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasComment("Route slug for navigation");

                    b.Property<string>("Summary")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasComment("Short summary shown in navigation");

                    b.Property<string>("SummaryDe")
                        .HasColumnType("TEXT")
                        .HasComment("Short summary shown in navigation (German)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("Update time");

                    b.HasKey("Id");

                    b.ToTable("InvoiceStages", t =>
                        {
                            t.HasComment("Invoice workflow stages");
                        });
                });

            modelBuilder.Entity("Oikos.Domain.Entities.Invoice.InvoiceStageHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("TEXT")
                        .HasComment("Change timestamp");

                    b.Property<int?>("ChangedByUserId")
                        .HasColumnType("INTEGER")
                        .HasComment("User identifier that performed the change");

                    b.Property<string>("ChangedByUserName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasComment("Name snapshot of the user that performed the change");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("INTEGER")
                        .HasComment("Invoice identifier");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasComment("Optional note about the change");

                    b.Property<int>("StageId")
                        .HasColumnType("INTEGER")
                        .HasComment("Stage identifier");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("StageId");

                    b.ToTable("InvoiceStageHistories", t =>
                        {
                            t.HasComment("History of invoice stage changes");
                        });
                });

            modelBuilder.Entity("Oikos.Domain.Entities.Log.LoginLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasComment("Primary key");

                    b.Property<string>("Agent")
                        .HasColumnType("TEXT")
                        .HasComment("Login client");

                    b.Property<string>("Ip")
                        .HasColumnType("TEXT")
                        .HasComment("Login IP");

                    b.Property<bool>("IsSuccessd")
                        .HasColumnType("INTEGER")
                        .HasComment("Was successful");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT")
                        .HasComment("Login time");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("Login name");

                    b.HasKey("Id");

                    b.HasIndex("Time");

                    b.HasIndex("UserName");

                    b.ToTable("LoginLogs", t =>
                        {
                            t.HasComment("Login log");
                        });
                });

            modelBuilder.Entity("Oikos.Domain.Entities.Partner.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasComment("Primary key");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasComment("Unique referral code");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasComment("Primary contact email");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("Creation timestamp (UTC)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasComment("Partner display name");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasComment("Internal notes");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Partners", t =>
                        {
                            t.HasComment("Lead partners");
                        });
                });

            modelBuilder.Entity("Oikos.Domain.Entities.Rbac.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasComment("Primary key");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("TEXT")
                        .HasComment("Consumption time (UTC)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("Creation time (UTC)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasComment("Expiration time (UTC)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("Token hash");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasComment("User identifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens", t =>
                        {
                            t.HasComment("Password reset tokens");
                        });
                });

            modelBuilder.Entity("Oikos.Domain.Entities.Rbac.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasComment("Primary key");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasComment("Is deleted");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasComment("Is enabled");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasComment("Role name");

                    b.HasKey("Id");

                    b.ToTable("Roles", t =>
                        {
                            t.HasComment("Role");
                        });
                });

            modelBuilder.Entity("Oikos.Domain.Entities.Rbac.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasComment("Primary key");

                    b.Property<string>("AcademicTitle")
                        .HasColumnType("TEXT")
                        .HasComment("Academic title");

                    b.Property<bool>("AcceptedPrivacyPolicy")
                        .HasColumnType("INTEGER")
                        .HasComment("Privacy policy accepted");

                    b.Property<string>("Avatar")
                        .HasColumnType("TEXT")
                        .HasComment("User avatar");

                    b.Property<string>("Company")
                        .HasColumnType("TEXT")
                        .HasComment("Company name");

                    b.Property<string>("CustomerNumber")
                        .HasColumnType("TEXT")
                        .HasComment("Customer number");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasComment("Email address");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT")
                        .HasComment("Gender");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasComment("Is deleted");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasComment("Is enabled");

                    b.Property<bool>("IsSpecial")
                        .HasColumnType("INTEGER")
                        .HasComment("Is special user");

                    b.Property<DateTime?>("LoginValiedTime")
                        .HasColumnType("TEXT")
                        .HasComment("Login failure tracking expiry");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("Username");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("INTEGER")
                        .HasComment("Referring partner id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("Password hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT")
                        .HasComment("Phone number");

                    b.Property<DateTime?>("PrivacyAcceptedAt")
                        .HasColumnType("TEXT")
                        .HasComment("Privacy policy accepted at");

                    b.Property<string>("RealName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("Full name");

                    b.Property<DateTime?>("SepaMandateGeneratedAt")
                        .HasColumnType("TEXT")
                        .HasComment("Timestamp of the latest generated SEPA mandate");

                    b.Property<string>("SepaMandatePath")
                        .HasColumnType("TEXT")
                        .HasComment("Relative path to the latest generated SEPA mandate for the user");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId");

                    b.ToTable("Users", t =>
                        {
                            t.HasComment("User");
                        });
                });

            modelBuilder.Entity("Oikos.Domain.Entities.Rbac.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasComment("Primary key");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER")
                        .HasComment("Role ID");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasComment("User ID");

                    b.HasKey("Id");

                    b.ToTable("UserRoles", t =>
                        {
                            t.HasComment("User role");
                        });
                });

            modelBuilder.Entity("Oikos.Domain.Entities.Setting.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasComment("Primary key");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("Key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("Value");

                    b.HasKey("Id");

                    b.ToTable("Settings", t =>
                        {
                            t.HasComment("System setting");
                        });
                });

            modelBuilder.Entity("Oikos.Domain.Entities.Setting.UserSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasComment("Primary key");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("Key");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasComment("User ID");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("Value");

                    b.HasKey("Id");

                    b.ToTable("UserSettings", t =>
                        {
                            t.HasComment("User setting");
                        });
                });

            modelBuilder.Entity("Oikos.Domain.Entities.Subscription.StripePayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasComment("Primary key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("Created timestamp");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("Customer email address");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasComment("Customer full name provided by Stripe");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("Raw webhook payload for auditing");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("TEXT")
                        .HasComment("Stripe customer id provided during checkout");

                    b.Property<string>("StripeSubscriptionId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("Stripe subscription id associated with the checkout session");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("Last update timestamp");

                    b.HasKey("Id");

                    b.ToTable("StripePayments", t =>
                        {
                            t.HasComment("Raw Stripe webhook data captured for purchases");
                        });
                });

            modelBuilder.Entity("Oikos.Domain.Entities.Subscription.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasComment("Primary key");

                    b.Property<string>("BillingInterval")
                        .HasColumnType("TEXT")
                        .HasComment("Billing interval reported by Stripe (monthly/yearly)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("Creation timestamp");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("TEXT")
                        .HasComment("Subscription expiration timestamp (UTC)");

                    b.Property<long?>("PriceAmount")
                        .HasColumnType("INTEGER")
                        .HasComment("Price amount in the smallest currency unit");

                    b.Property<string>("PriceCurrency")
                        .HasColumnType("TEXT")
                        .HasComment("Three-letter ISO currency code for the subscription price");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT")
                        .HasComment("Purchase timestamp (UTC)");

                    b.Property<int>("StripePaymentId")
                        .HasColumnType("INTEGER")
                        .HasComment("Foreign key to the captured Stripe payment");

                    b.Property<string>("StripeSubscriptionId")
                        .HasColumnType("TEXT")
                        .HasComment("Stripe subscription identifier");

                    b.Property<int?>("SubscriptionPlanId")
                        .HasColumnType("INTEGER")
                        .HasComment("Linked subscription plan derived from Stripe metadata");

                    b.Property<string>("SubscriptionType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("Subscription type derived from Stripe PriceId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("Last update timestamp");

                    b.HasKey("Id");

                    b.HasIndex("StripePaymentId");

                    b.HasIndex("SubscriptionPlanId");

                    b.ToTable("Subscriptions", t =>
                        {
                            t.HasComment("Represents a purchased subscription mapped from Stripe checkout sessions");
                        });
                });

            modelBuilder.Entity("Oikos.Domain.Entities.Subscription.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasComment("Primary key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("Creation timestamp");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasComment("Plan description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER")
                        .HasComment("Display ordering");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasComment("Whether the plan is available for purchase");

                    b.Property<int?>("MonthlyBionicCheckLimit")
                        .HasColumnType("INTEGER")
                        .HasComment("Monthly bionic company check limit");

                    b.Property<int?>("MonthlyClaimLimit")
                        .HasColumnType("INTEGER")
                        .HasComment("Monthly claim submission limit");

                    b.Property<decimal>("MonthlyPrice")
                        .HasColumnType("TEXT")
                        .HasComment("Monthly price in euros");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("Display name shown to users");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("Unique slug for internal references");

                    b.Property<int?>("TeamSeatLimit")
                        .HasColumnType("INTEGER")
                        .HasComment("Maximum team members allowed; null means unlimited");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("Last update timestamp");

                    b.Property<decimal>("YearlyPrice")
                        .HasColumnType("TEXT")
                        .HasComment("Yearly price in euros");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans", t =>
                        {
                            t.HasComment("Defines a purchasable subscription plan with feature limits");
                        });
                });

            modelBuilder.Entity("Oikos.Domain.Entities.Subscription.UserSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasComment("Primary key");

                    b.Property<DateTime>("ActivationDate")
                        .HasColumnType("TEXT")
                        .HasComment("Activation timestamp (UTC)");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("INTEGER")
                        .HasComment("Auto renew flag");

                    b.Property<string>("BillingInterval")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("Billing interval: monthly/yearly");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("Creation timestamp");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("TEXT")
                        .HasComment("Optional expiration timestamp (UTC)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("Status: active, cancelled, expired");

                    b.Property<int>("SubscriptionPlanId")
                        .HasColumnType("INTEGER")
                        .HasComment("Subscribed plan");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("Last update timestamp");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasComment("User id");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionPlanId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSubscriptions", t =>
                        {
                            t.HasComment("Tracks the active subscription plan for a user");
                        });
                });

            modelBuilder.Entity("Oikos.Domain.Entities.Invoice.Invoice", b =>
                {
                    b.HasOne("Oikos.Domain.Entities.Invoice.InvoiceStage", "Stage")
                        .WithMany("Invoices")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("Oikos.Domain.Entities.Invoice.InvoiceStageHistory", b =>
                {
                    b.HasOne("Oikos.Domain.Entities.Invoice.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oikos.Domain.Entities.Invoice.InvoiceStage", "Stage")
                        .WithMany("Histories")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("Oikos.Domain.Entities.Rbac.PasswordResetToken", b =>
                {
                    b.HasOne("Oikos.Domain.Entities.Rbac.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Oikos.Domain.Entities.Rbac.User", b =>
                {
                    b.HasOne("Oikos.Domain.Entities.Partner.Partner", "Partner")
                        .WithMany("Users")
                        .HasForeignKey("PartnerId");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("Oikos.Domain.Entities.Subscription.Subscription", b =>
                {
                    b.HasOne("Oikos.Domain.Entities.Subscription.StripePayment", "StripePayment")
                        .WithMany("Subscriptions")
                        .HasForeignKey("StripePaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oikos.Domain.Entities.Subscription.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany()
                        .HasForeignKey("SubscriptionPlanId");

                    b.Navigation("StripePayment");

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("Oikos.Domain.Entities.Subscription.UserSubscription", b =>
                {
                    b.HasOne("Oikos.Domain.Entities.Subscription.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oikos.Domain.Entities.Rbac.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriptionPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Oikos.Domain.Entities.Invoice.InvoiceStage", b =>
                {
                    b.Navigation("Histories");

                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("Oikos.Domain.Entities.Partner.Partner", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Oikos.Domain.Entities.Rbac.User", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Oikos.Domain.Entities.Subscription.StripePayment", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Oikos.Domain.Entities.Subscription.SubscriptionPlan", b =>
                {
                    b.Navigation("UserSubscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
